FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["src/Woodpecker.Web/Woodpecker.Web.csproj", "src/Woodpecker.Web/"]
RUN dotnet restore "src/Woodpecker.Web/Woodpecker.Web.csproj"

COPY src/Woodpecker.Web/ src/Woodpecker.Web/
RUN dotnet publish "src/Woodpecker.Web/Woodpecker.Web.csproj" -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "Woodpecker.Web.dll"]
