// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Woodpecker.Infrastructure;

#nullable disable

namespace Woodpecker.Infrastructure.Migrations
{
    [DbContext(typeof(WoodpeckerDbContext))]
    [Migration("20261007151809_AddCycleAbandonedAt")]
    partial class AddCycleAbandonedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Woodpecker.Domain.Puzzle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Fen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("SolutionMoves")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Puzzles", (string)null);
                });

            modelBuilder.Entity("Woodpecker.Domain.PuzzleAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PuzzleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrainingCycleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PuzzleId");

                    b.HasIndex("TrainingCycleId");

                    b.ToTable("PuzzleAttempts", (string)null);
                });

            modelBuilder.Entity("Woodpecker.Domain.PuzzleSet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("PuzzleSets", (string)null);
                });

            modelBuilder.Entity("Woodpecker.Domain.PuzzleSetItem", b =>
                {
                    b.Property<Guid>("PuzzleSetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PuzzleId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("PuzzleSetId", "PuzzleId");

                    b.HasIndex("PuzzleId");

                    b.ToTable("PuzzleSetItems", (string)null);
                });

            modelBuilder.Entity("Woodpecker.Domain.TrainingCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AbandonedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CycleNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("PuzzleSetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PuzzleSetId");

                    b.HasIndex("UserId");

                    b.ToTable("TrainingCycles", (string)null);
                });

            modelBuilder.Entity("Woodpecker.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Woodpecker.Domain.PuzzleAttempt", b =>
                {
                    b.HasOne("Woodpecker.Domain.TrainingCycle", null)
                        .WithMany("_attempts")
                        .HasForeignKey("TrainingCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Woodpecker.Domain.PuzzleSetItem", b =>
                {
                    b.HasOne("Woodpecker.Domain.Puzzle", null)
                        .WithMany()
                        .HasForeignKey("PuzzleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Woodpecker.Domain.PuzzleSet", null)
                        .WithMany("_items")
                        .HasForeignKey("PuzzleSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Woodpecker.Domain.PuzzleSet", b =>
                {
                    b.Navigation("_items");
                });

            modelBuilder.Entity("Woodpecker.Domain.TrainingCycle", b =>
                {
                    b.Navigation("_attempts");
                });
#pragma warning restore 612, 618
        }
    }
}
